=head1 NAME

finnix-strace-reorder.experimental - A program to produce 
genisoimage/mksquashfs order files (experimental version)

=head1 SYNOPSIS

B<finnix-strace-reorder.experimental> <I<strace output> >I<order file>

=head1 DESCRIPTION

For more information, see B<finnix-strace-reorder>.

This was an experimental variation of B<finnix-strace-reorder>, using 
the average/probable distance between files as a consideration as to 
where to place at the front of the CD, rather than simply ordering the 
front of the image according to how many times a file is opened during 
boot.  It uses simulated annealing to determine positioning, and will 
run forever until cancelled, printing out the best order it has found 
so far.

For various reasons, this method was not used, and this script is not 
being maintained.

=head1 OPTIONS

Unknown

=head1 BUGS

This script is not maintained.

=head1 AUTHOR

B<finnix-strace-reorder.experimental> was written by Ryan Finnie 
<ryan@finnie.org>, with algorithm contributions by Randall Munroe and 
Emad El-Haraty.

=cut

