=head1 NAME

finnix-strace-reorder.classic - A program to produce genisoimage/mksquashfs 
order files

=head1 SYNOPSIS

B<finnix-strace-reorder.classic> <I<strace output> >I<order file>

=head1 DESCRIPTION

B<finnix-strace-reorder.classic> takes input in the form of strace data 
(collected during Finnix boot by the "finnix strace" boot option, and 
stored in /var/log/), determines which files are being opened or 
executed, and returns them, along with a weight.  The weight is 
determined by the number of times the file is loaded.

This output can then be fed to genisoimage's or mksquashfs's "-sort 
sortfile" argument to place files used during boot at the front of the 
image.

=head1 OPTIONS

None.

=head1 BUGS

More frequently used files are given a higher weight, placing them at 
the front of the image (CD).  Since CD-ROM drives use constant linear 
velocity, frequently used files should probably be given a high 
negative weight, placing them at the back of the image for faster read 
rates.  This should probably be the default, and overridden with a 
program flag.

No exclusions are made, so files like kernel modules are included.  
Some modules are constant to all boots, but many depend on the 
hardware, so they are of little use being at the front of the image.

=head1 AUTHOR

B<finnix-strace-reorder.classic> was written by Ryan Finnie <ryan@finnie.org>.

=cut

