=head1 NAME

fstype - Determine the filesystem type of a block device

=head1 SYNOPSIS

B<fstype> I</dev/device>

=head1 DESCRIPTION

B<fstype> determines the type of a filesystem block device, suitable 
for inclusion in the third column of /etc/fstab.  If the filesystem 
type can be determined, it is written to STDOUT.  If not, no output is 
returned.

=head1 OPTIONS

None.

=head1 BUGS

The list of filesystem types to check for is currently hard coded.

=head1 AUTHOR

B<fstype> was written by Klaus Knopper for Knoppix, and modified for 
Finnix by Ryan Finnie <ryan@finnie.org>.

=cut

