=head1 NAME

notfound - A simple "command not found" informational program

=head1 SYNOPSIS

B<notfound> I<command> S<[ ignored arguments ]>

=head1 DESCRIPTION

B<notfound> is an informational program, similar to the 
B<command-not-found> program, but simpler and hardcoded for use by 
Finnix.  It is designed to be used from /etc/bash.bashrc or 
/etc/profile e.g.:

    alias lynx='notfound lynx'

In this example, if lynx is not installed, a message is given 
explaining so, and how to install it.  If it is installed, it is 
executed, along with any originally supplied arguments.

=head1 OPTIONS

All arguments past the specified command are either ignored, or passed 
to the real program

=head1 BUGS

The programs caught and informational messages are hardcoded into the 
script itself.

=head1 AUTHOR

B<notfound> was written by Ryan Finnie <ryan@finnie.org>.

=cut

