=head1 NAME

rebuildfstab - Dynamically update /etc/fstab

=head1 SYNOPSIS

B<rebuildfstab>

=head1 DESCRIPTION

B<rebuildfstab> scans for block devices.  If it determines a block 
device is a valid filesystem, a corresponding directory is added to 
/media, and a line in /etc/fstab is added.  Filesystems that disappear 
are removed from /etc/fstab.

On Finnix systems, B<rebuildfstab> is executed by udev automatically 
upon block device changes (hotplugs, etc).  It can also be run 
manually, and takes steps to detect and avoid concurrent runs.

=head1 OPTIONS

None.

=head1 BUGS

None known at this time.

=head1 AUTHOR

B<rebuildfstab> was written by Ryan Finnie <ryan@finnie.org>.  It is a 
rewrite of a script of the same name by Klaus Knopper.

=cut

