=head1 NAME

zram_stat - A simple utility for zram usage

=head1 SYNOPSIS

B<zram_stat>

=head1 DESCRIPTION

B<zram_state> is a utility for getting basic information about the 
running zram mount, zram is in use.

=head1 OPTIONS

None.

=head1 BUGS

The script is hardcoded to zram0, and has few sanity checks.

=head1 AUTHOR

B<zram_stat> was written by John Moser <john.r.moser@gmail.com>.

=cut
