#!/bin/sh

### BEGIN INIT INFO
# Provides:          finnix-autoconfig-locale
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Shoft-Description: Set up locale, time zone, etc
### END INIT INFO

# finnix-autoconfig-locale
# Copyright (C) 2012 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

umask 022

case "$1" in
  start) ;;
  stop|restart|force-reload) exit 0 ;;
  *) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

. /lib/finnix/finnix-rc-helper.sh

# Nice default
TZ="UTC"

# Set clock
#UTC="-u "
KTZ="$(getbootparam tz)"
[ -f "/usr/share/zoneinfo/$KTZ" ] && TZ="$KTZ"
# hwclock uses the TZ variable
export TZ
rm -f /etc/adjtime
if checkbootparam "nohwclock"; then
  if [ "${FINNIX_XENU}" = "no" ] && [ "${FINNIX_UML}" = "no" ]; then
    _f12 hwclock $UTC -s
  fi
fi
rm -f /etc/localtime
cp "/usr/share/zoneinfo/$TZ" /etc/localtime

KEYTABLE="$(getbootparam keyboard)"
if [ -n "$KEYTABLE" ] && which loadkeys >/dev/null 2>/dev/null; then
  _f12 loadkeys -q "$KEYTABLE"
fi

if checkbootparam "0" && \
  which loadkeys >/dev/null 2>/dev/null && \
  [ -f /usr/share/console/lists/console-data.keymap-list ]; then
  (
    export TERM=linux
    REALDEV="/dev/$(cat /sys/dev/char/4:0/active)"
    exec chpst -P /bin/bash -i -c /usr/sbin/finnix-keyboard-choose >"$REALDEV" 2>"$REALDEV" <"$REALDEV"
  )
fi

CONSOLEFONT="$(getbootparam font)"
if which setfont >/dev/null 2>/dev/null; then
  if [ -n "$CONSOLEFONT" ]; then
    _f12 setfont "$CONSOLEFONT"
  else
    _f12 setfont
  fi
fi
