#!/bin/sh

### BEGIN INIT INFO
# Provides:          finnix-autoconfig-fstab
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Shoft-Description: Build /etc/fstab
### END INIT INFO

# finnix-autoconfig-fstab
# Copyright (C) 2012 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

umask 022

case "$1" in
  start) ;;
  stop|restart|force-reload) exit 0 ;;
  *) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

. /lib/finnix/finnix-rc-helper.sh

if checkbootparam "nofstab"; then
  exit 0
fi

echo -n "${BLUEITEM} Scanning for partitions and creating ${WHITE}/etc/fstab${NORMAL}... "
# Next line shouldn't be needed if udev finnix.rules hasn't been loaded yet (see below).
# Still, it doesn't hurt to leave it in.
while [ -f "/var/run/rebuildfstab.pid" -a -e "/proc/$(_f2 cat /var/run/rebuildfstab.pid)" ]; do sleep 1; done

_f12 rebuildfstab

# Now it's safe to load finnix.rules.
ln -sf ../finnix.rules /etc/udev/rules.d/z90_finnix.rules
if ! checkbootparam "nohwsetup"; then
  udevadm control --reload-rules
fi

echo -n "done${CRE}"
