#!/bin/sh

### BEGIN INIT INFO
# Provides:          finnix-autoconfig
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Shoft-Description: Finnix configuration and hardware setup
### END INIT INFO

# finnix-autoconfig
# Copyright (C) 2012 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

umask 022

case "$1" in
  start) ;;
  stop|restart|force-reload) exit 0 ;;
  *) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

# Mount /proc and /sys
[ -f /proc/version ] || mount -t proc none /proc >/dev/null 2>/dev/null
[ -d /sys/devices ] || mount -t sysfs none /sys >/dev/null 2>/dev/null

. /lib/finnix/finnix-rc-helper.sh

# Let's see if we can get rid of that "INIT:" message
echo -n "${CRE}${ESC}[1A${CRE}"
echo -n "${CRE}${ESC}[1A${CRE}"

# Print CPU info
SYSNAME="$(uname -s)"
KERNEL="$(uname -r)"
echo "${BLUEITEM} System: ${WHITE}$(finnix-pretty-cpu)${NORMAL}"
echo "${BLUEITEM} Running $SYSNAME kernel ${WHITE}$KERNEL${NORMAL} on ${WHITE}$ARCH${NORMAL}"

# Get rid of the initrd
_f12 umount /initrd

# Set hostname
hostname `cat /etc/hostname`

# Remove runit shutdown/reboot config files, if they happen to exist
rm -f /var/run/runit-control-reboot
rm -f /var/run/runit-control-stopit
