#!/bin/sh

for i in OS_NAME OS_VERSION; do
  read "$i"
done <<EOM
$(
  . /etc/os-release
  echo "$NAME"
  echo "$VERSION"
)
EOM
. /lib/finnix/finnix-rc-helper.sh

case "$1" in
  start)
    STATINFO="$(_f2 stat -t -f /media/compressed_root)"
    if [ -n "$STATINFO" ]; then
      while read SUNDEF1 SUNDEF2 SUNDEF3 SUNDEF4 SBLOCKSIZE SUNDEF5 SBLOCKS SUNDEF6; do
        CDSIZE="$(($SBLOCKSIZE * $SBLOCKS / 1048576))M"
      done <<EOM
$STATINFO
EOM
      if [ -n "$CDSIZE" ]; then
        ONA=", ${WHITE}$CDSIZE${NORMAL} compressed"
      fi
    fi
    PACKAGESINSTALLED="`dpkg -l | egrep '^[hi]i' | wc -l`"
    echo "${BLUEITEM} ${BLUE}${OS_NAME}${NORMAL} ${WHITE}${OS_VERSION}${NORMAL} ready; ${WHITE}$PACKAGESINSTALLED${NORMAL} packages${ONA}"
    echo
    ;;
  *)
    echo "Usage: $0 {start}" >&2
    exit 1
    ;;
esac
