#!/bin/sh

. /lib/finnix/finnix-rc-helper.sh

[ "${FINNIX_XENU}" = "yes" ] && exit 0
[ "${FINNIX_UML}" = "yes" ] && exit 0

case "$1" in
  start)
    checkbootparam "nomouse" && exit 0
    if can_invoke_rcd gpm start; then
      echo -n "${BLUEITEM} Starting mouse services... "
      _f12 invoke-rc.d gpm start
      echo -n "done${CRE}"
    fi
    ;;
  stop)
    if can_invoke_rcd gpm stop; then
      _f12 invoke-rc.d gpm stop
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

exit 0


