#!/bin/sh

### BEGIN INIT INFO
# Provides:          finnix-autoconfig-thermal
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Shoft-Description: Set up udev
### END INIT INFO

# finnix-autoconfig-thermal
# Copyright (C) 2013 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Partially adapted from Debian initramfs-tools

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

umask 022

case "$1" in
  start) ;;
  stop|restart|force-reload) exit 0 ;;
  *) echo "Usage: $0 {start|stop|restart|force-reload}" >&2; exit 1 ;;
esac

. /lib/finnix/finnix-rc-helper.sh

case "$(dpkg --print-architecture)" in
powerpc|ppc64)
	# Only G5 Mac machines need to load
	# therm_pm72 or one of the windfarm_pm* modules.

	[ -r /proc/cpuinfo ] || exit 0
	MODEL="`grep model /proc/cpuinfo`"
	MODEL="${MODEL##*: }"

	case "$MODEL" in
	  RackMac3,1|PowerMac7,2|PowerMac7,3)
	    _f12 modprobe therm_pm72
	    ;;
	  PowerMac8,1|PowerMac8,2)
	    _f12 modprobe windfarm_pm81
	    ;;
	  PowerMac9,1)
	    _f12 modprobe windfarm_pm91
	    ;;
	  PowerMac11,2)
	    _f12 modprobe windfarm_pm112
	    ;;
	  PowerMac12,1)
	    _f12 modprobe windfarm_pm121
	    ;;
	esac
	;;
esac
