#!/bin/sh

. /lib/finnix/finnix-rc-helper.sh

case "$1" in
  start)
    if checkbootparam "sshd"; then
      if [ "`egrep '^root:' /etc/shadow | awk -F: '{print $2}'`" = \* ]; then
        ROOTPASS_USER="$(getbootparam sshd_password)"
        if [ -n "${ROOTPASS_USER}" ]; then
          ROOTPASS="${ROOTPASS_USER}"
        else
          ROOTPASS="$(pwgen)"
        fi
        chpasswd --md5 <<EOM
root:$ROOTPASS
finnix:$ROOTPASS
EOM
      fi
      invoke-rc.d ssh start
      if [ -n "${ROOTPASS}" ]; then
        echo "${BLUEITEM}   New root/finnix password: ${WHITE}${ROOTPASS}${NORMAL}"
      fi
      echo -n "${BLUEITEM} Waiting... "; sleep 5; echo -n "done${CRE}"
      echo "${BLUEITEM}   Current system IP addresses:"
      ip addr | grep inet | grep "scope global"
    fi
    ;;
  stop)
    if _f12 invoke-rc.d ssh status; then
      invoke-rc.d ssh stop
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
