#!/bin/sh

### BEGIN INIT INFO
# Provides:          motd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Create dynamic part of /etc/motd
# Description:       /etc/motd is user-editable and static.  This script
#                    creates the initial dynamic part, by default the
#                    output of uname, and stores it in /run/motd.dynamic.
#                    Both parts are output by pam_motd.
### END INIT INFO

. /lib/finnix/finnix-rc-helper.sh

if can_invoke_rcd motd "$@"; then
  exec invoke-rc.d motd "$@"
fi
