#!/bin/sh

set -e

KEYSDIR="$1"
SERIESFILE="$2"
DESTRING="$3"

[ -z "$KEYSDIR" ] && exit 1
[ -z "$SERIESFILE" ] && exit 1
[ -z "$DESTRING" ] && exit 1
[ -e "$SERIESFILE" ] || exit 1

TEMPHOME="$(mktemp -d)"

for i in $(grep -v '^\s*\#' "$SERIESFILE"); do
  gpg1 --batch --no-tty --no-options --homedir "$TEMPHOME" --import "$KEYSDIR/$i"
done

cat "$TEMPHOME/pubring.gpg" >"$DESTRING"
chmod 0644 "$DESTRING"
rm -rf "$TEMPHOME"
