#!/usr/bin/python

# reprepro-launchpad-announce
# Copyright (C) 2012 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import rppla
import sys


def main(argv):
    try:
        import config as config_user
    except ImportError:
        print >> sys.stderr, 'config.py is needed, please see README'
        return(1)
    config = rppla.Config(config_user)

    if len(argv) > 1 and argv[1] == 'launchpad-login':
        return(rppla.launchpad_login(config))
    elif len(argv) == 6 and argv[1] == 'accepted':
        return(rppla.process_changes(config, *argv[2:6]))
    else:
        print >> sys.stderr, 'Usage:'
        print >> sys.stderr, '    %s launchpad-login' % argv[0]
        print >> sys.stderr, '    %s accepted <codename> <source package> <version> <changes file>' % argv[0]
        return(1)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
