#!/bin/bash

# This hook is needed because Finnix netboot clients (with a root indirectly
# mounted via NFS) come across the new dhclient-script, and the first thing
# it does is clear the IP address on the interface.  NFS doesn't like that.
# This hook will only bring the interface up (and clear it) if it's
# currently down.  It then disrupts dhclient-script's internal handling so
# the PREINIT code cannot clear the interface's IP.

if [ "$reason" = "PREINIT" ]; then
  # Only bring the interface up if it's down
  if [ "$(cat /sys/class/net/$interface/operstate)" = "down" ]; then
    ip link set dev $interface up
  fi

  # Prevent the dhclient-script from executing its own internal code
  export reason=NONE
fi
