#!/bin/sh
set -e

if [ "$1" = configure ]; then
    if [ -e /etc/default/grub-finnix ]; then
      . /etc/default/grub-finnix
    fi
    if [ -z "$FINNIX_ISO" ]; then
        echo
        echo "Notice: grub-finnix must be configured before use.  Please edit"
        echo "/etc/default/grub-finnix, specify the location of the Finnix ISO(s),"
        echo "then run 'update-grub2'."
        echo
    fi
    if [ -e /boot/grub/grub.cfg ] && [ -x "`which update-grub2 2>/dev/null`" ] ; then
	update-grub2
    fi
fi

#DEBHELPER#
