#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = remove ]; then
  for fn in /etc/lsb-release /etc/os-release; do
    if [ -e "$fn.distrib" ]; then
      rm -f "$fn"
      dpkg-divert --rename --package finnix-scripts --divert "$fn.distrib" --remove "$fn"
    fi
  done
fi
