#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = remove ]; then
  # Remove diversions
  for fn in /etc/lsb-base-logging.sh /sbin/init /sbin/telinit; do
    if [ -e "$fn.distrib" ]; then
      rm -f "$fn"
      dpkg-divert --rename --package finnix-scripts --divert "$fn.distrib" --remove "$fn"
    fi
  done

  # Remove /etc/init.d/runit diversion
  if [ -e /lib/finnix/init.d/ssh.distrib ]; then
    rm -f /etc/init.d/ssh
    dpkg-divert --rename --package finnix-scripts --divert /lib/finnix/init.d/ssh.distrib --remove /etc/init.d/ssh
  fi

  # Remove finnix user
  if getent passwd finnix >/dev/null 2>/dev/null; then
    userdel finnix
  fi

  # Remove runit shutdown/reboot files
  rm -f /etc/runit/reboot
  rm -f /etc/runit/stopit
fi
