#!/bin/sh

# finnix-generate-entropy
# Copyright (C) 2011 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

for i in OS_NAME; do
  read "$i"
done <<EOM
$(
  . /etc/os-release
  echo "$NAME"
)
EOM

### Utility Function(s)
do_whiptail() {
  DTMP=`mktemp`
  whiptail --output-fd 3 --backtitle "${OS_NAME}" --title "${OS_NAME} Entropy Generation" "$@" 3>${DTMP}
  DOUT=$?
  DVAL="$(cat ${DTMP})"
  rm -f ${DTMP}
  return ${DOUT}
}

POOLSIZE="$(($(cat /proc/sys/kernel/random/poolsize)/8))"
[ -z "$POOLSIZE" ] && POOLSIZE=4096
while true; do
  do_whiptail --inputbox "This program generates cryptographic entropy normally missing due to the LiveCD environment.  It is recommended that you generate $POOLSIZE bytes of entropy (the size of an entropy pool on this system), though the process is slow; approximately 1 second per 32 bytes.\n\nHow many bytes of entropy would you like to generate?" 0 0 "$POOLSIZE"
  [ $? -eq 0 ] || exit
  POOLSIZE="$DVAL"
  [ -n "$POOLSIZE" ] && break
done

echo; echo; echo
if which rndaddentropy >/dev/null 2>/dev/null; then
  twuewand "$POOLSIZE" | rndaddentropy
else
  twuewand "$POOLSIZE" >/dev/random
fi
echo; echo
sleep 3
exit 0
