#!/bin/sh

# finnix-keyboard-choose
# Copyright (C) 2014 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

for i in OS_NAME OS_VERSION OS_VERSION_ID OS_ID; do
  read "$i"
done <<EOM
$(
  . /etc/os-release
  echo "$NAME"
  echo "$VERSION"
  echo "$VERSION_ID"
  echo "$ID"
)
EOM

do_whiptail() {
  DTMP=`mktemp`
  whiptail --output-fd 3 --backtitle "${OS_NAME}" --title "${OS_NAME} Keyboard Configuration" "$@" 3>${DTMP}
  DOUT=$?
  DVAL="$(cat ${DTMP})"
  rm -f ${DTMP}
  return ${DOUT}
}

[ -f /usr/share/console/lists/console-data.keymap-list ] || exit 0

if do_whiptail --noitem --menu "Please select a keyboard layout" 0 0 0 \
  defkeymap "Keymap" \
  $(awk '{print $2" Keymap"}' /usr/share/console/lists/console-data.keymap-list | sort); then
  loadkeys -q "$DVAL" >/dev/null 2>/dev/null
fi
