#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

# NB: Only bash and busybin ash are supported, due to requiring
# "read -t"
if [ -x /media/ramdisk/busybin/sh ]; then
  # Using busybin allows for clean CD ejection
  cp /etc/runit/state-shutdown-real /media/ramdisk/busybin/
  cd /
  exec /media/ramdisk/busybin/sh /media/ramdisk/busybin/state-shutdown-real "$@"
else
  cd /
  exec /bin/bash /etc/runit/state-shutdown-real "$@"
fi
