#!/bin/bash

# Note: While the shebang says /bin/bash, this script must be written to
# also be run as a busybox ash script (a small superset of POSIX shell).
# The only reason it's not /bin/sh is because of "read -t", which is
# supported in bash and ash, but not POSIX shell.

# state-shutdown-real
# Copyright (C) 2013 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

PATH=/bin:/sbin:/usr/bin:/usr/sbin

. /lib/finnix/finnix-rc-helper.sh

# Run a shell if in debug mode
rundebugshell() {
  echo "${BLUEITEM} Starting debug shell."
  echo "${BLUEITEM} Type \"exit\" to continue."
  _f12 which bash && bash || sh
}

# Let's see if we can get rid of that "INIT:" message
echo -n "${CRE}${ESC}[1A${CRE}"
echo -n "${CRE}${ESC}[1A${CRE}"
echo

if [ -x /etc/runit/reboot -o "$SHUTDOWN_TYPE" = "reboot" ]; then
  SHUTDOWN_TYPE="reboot"
  message="Rebooting"
  message2="reboot"
  command="reboot"
  options="-f -n"
else
  SHUTDOWN_TYPE="poweroff"
  message="Shutting down"
  message2="shut down"
  command="poweroff"
  options="-f -n"
fi

cd /

# Now umount everything but root
echo -n "${BLUEITEM} Unmounting remaining file systems... "

if [ -x /media/ramdisk/busybin/sh -a -z "$PIVOTED_RAMDISK" ]; then
  mkdir -p /media/ramdisk/tmp
  chmod 1777 /media/ramdisk/tmp

  mkdir -p /media/ramdisk/lib/finnix
  cp -a /lib/finnix/*.sh /media/ramdisk/lib/finnix/

  mkdir -p /media/ramdisk/proc
  mount -t proc proc /media/ramdisk/proc
  mkdir -p /media/ramdisk/sys
  mount -t sysfs sysfs /media/ramdisk/sys
  mkdir -p /media/ramdisk/dev
  mount -n -t devtmpfs none /media/ramdisk/dev

  cd /media/ramdisk
  mkdir -p oldroot
  pivot_root . oldroot
  PIVOTED_RAMDISK=true SHUTDOWN_TYPE="$SHUTDOWN_TYPE" exec ./busybin/chroot . /busybin/sh /busybin/state-shutdown-real >./dev/console 2>&1 <./dev/console
fi

if [ -x /busybin/sh ]; then
  PATH=/busybin
  hash -r

  # We should be able to umount everything under the old union root
  for mount in $(awk '$2 ~ "^/oldroot" { print $2 }' /proc/mounts); do
    _f12 umount -dfl "$mount"
  done
  _f12 rmdir /oldroot

  # Remove unused files to save space
  _f12 rm -rf /union_writable
  _f12 rm -rf /cd_base

  # Now we should be able to umount the rest.
  for mount in $(awk '$3 !~ "^(tmpfs|sysfs|proc|rootfs|devtmpfs)$" { print $2 }' /proc/mounts); do
    _f12 umount -drfl "$mount"
  done
else
  # umount everything we can, everything else is ro
  for mount in $(awk '$3 !~ "^(tmpfs|sysfs|proc|rootfs|devtmpfs)$" { print $2 }' /proc/mounts); do
    _f12 umount -dr "$mount"
  done
fi

# Remove remaining unused modules
_f12 rmmod -a

echo -n "done${CRE}"

# Sync the buffers and disable CAD init handling in preparation for reboot countdown
# (Yes, I'm old school and still sync twice)
sync; sync;
[ -e /proc/sys/kernel/ctrl-alt-del ] && echo 1 >/proc/sys/kernel/ctrl-alt-del

# Eject the CD
if [ "${FINNIX_NOEJECT}" = "no" ]; then
  if [ -n "${FINNIX_DEV}" ]; then
    _f12 eject "${FINNIX_DEV}"
  fi
fi

# Thank you, you've been a great audience.
echo "${CRE}${BLUEITEM} It is now safe to shut down/reboot."
for i in 10 9 8 7 6 5 4 3 2 1; do
  echo -n "${CRE}${BLUEITEM} $message in $i (or press ENTER to $message2 immediately)..."
  # Give the user an opportunity to press Enter to immediately shut
  # down/reboot, or "d" to get to the debug shell.
  if read -t 1 -n 1 READCMD; then
    echo -n "${CRE}"
    if [ -z "$READCMD" ]; then
      break
    elif [ "$READCMD" = "d" ]; then
      FINNIX_DEBUG="yes"
      break
    fi
  fi
done

[ "${FINNIX_DEBUG}" = "yes" ] && rundebugshell
echo "${CRE}${BLUEITEM} $message..."
exec $command $options
