#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

. /lib/finnix/finnix-rc-helper.sh

# Let's see if we can get rid of that "INIT:" message
echo -n "${CRE}${ESC}[1A${CRE}"
echo -n "${CRE}${ESC}[1A${CRE}"

export RUNLEVEL=2
if [ -x /usr/sbin/finnix-utmp ]; then
  /usr/sbin/finnix-utmp runlevel $RUNLEVEL
fi
/etc/finnix/init.d/rc $RUNLEVEL

exec env - PATH=$PATH \
runsvdir -P /lib/finnix/service/running 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
